# MerMer Default Config

title = "TideWallet-Backend"

[base]
folder = "TideWallet-Backend"
static = "./build/frontend/"
token_secret_expire_time = 31536000 # 365 * 24 * 60 * 60 (expires in 365 day)
debug = false

[ethereum]
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[ethereum.ropsten]
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[bitcoin]
protocol = "http:"
hostname = "127.0.0.1"
port = 18332
path = "/"
user = ''
password = ''

[syncInterval]
ethereum = 15000
bitcoin = 900000

[database]
protocol = "postgres"
host = "postgres"
port = ""
user = ""
password = ""
dbName = ""
logging = false
autoReconnect = true
ormEnable = true
  [database.dialectOptions]
  connectTimeout = 3000

  [database.pool]
  max = 100

[jwt]
secret = ""

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/v1/blockchain | Bot.Blockchain.BlockchainList",
  "get | /api/v1/blockchain/:blockchain_id | Bot.Blockchain.BlockchainDetail",
  "get | /api/v1/currency | Bot.Blockchain.CurrencyList",
  "get | /api/v1/currency/:currency_id | Bot.Blockchain.CurrencyDetail",
  "get | /api/v1/blockchain/:blockchain_id/token | Bot.Blockchain.TokenList",
  "get | /api/v1/blockchain/:blockchain_id/token/:token_id | Bot.Blockchain.TokenDetail",
  "post | /api/v1/user | Bot.User.UserRegist",
  "get | /api/v1/token/verify | Bot.User.AccessTokenVerify",
  "post | /api/v1/token/renew | Bot.User.AccessTokenRenew",
  "post | /api/v1/wallet/blockchain/:blockchain_id/token/:currency_id | Bot.Account.TokenRegist",
  "get | /api/v1/wallet/accounts | Bot.Account.AccountList",
  "get | /api/v1/wallet/account/:currency_id | Bot.Account.AccountDetail",
  "get | /api/v1/wallet/account/address/:account_id/receive | Bot.Account.AccountReceive",
  "get | /api/v1/wallet/account/address/:account_id/change | Bot.Account.AccountChange",
  "get | /api/v1/wallet/account/txs/:account_id | Bot.Account.ListTransactions",
  "get | /tool/drop | Bot.Account.DROP_ALL_TABLE"
]