# MerMer Default Config

title = "TideWallet-Backend"

[base]
folder = "TideWallet-Backend"
static = "./build/frontend/"
token_secret_expire_time = 31536000 # 365 * 24 * 60 * 60 (expires in 365 day)
debug = false

[blockchain]
type = "ethereum"

[database]
protocol = "postgres"
host = "postgres"
port = ""
user = ""
password = ""
dbName = ""
logging = false
autoReconnect = true
ormEnable = true
  [database.dialectOptions]
  connectTimeout = 3000

  [database.pool]
  max = 100

[jwt]
secret = ""

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/v1/blockchain | Bot.Blockchain.BlockchainList",
  "get | /api/v1/blockchain/:blockchain_id | Bot.Blockchain.BlockchainDetail",
  "get | /api/v1/currency | Bot.Blockchain.CurrencyList",
  "get | /api/v1/currency/:currency_id | Bot.Blockchain.CurrencyDetail",
  "get | /api/v1/blockchain/:blockchain_id/token | Bot.Blockchain.TokenList",
  "get | /api/v1/blockchain/:blockchain_id/token/:token_id | Bot.Blockchain.TokenDetail",
  "post | /api/v1/user | Bot.User.UserRegist",
  "get | /api/v1/token/verify | Bot.User.AccessTokenVerify",
  "post | /api/v1/token/renew | Bot.User.AccessTokenRenew"
]