[database]
protocol = "postgres"
host = "127.0.0.1"
port = "5432"
user = "postgres"
password = "admin"
dbName = "postgres"
logging = false
autoReconnect = true
ormEnable = true
  [database.dialectOptions]
  connectTimeout = 3000

  [database.pool]
  max = 100